[package]
name = "pi"
version = "0.1.0"
authors = ["Sergio Benitez <sb@sergio.bz>"]

[dependencies]
std = { path = "../std" } # Use customized std
volatile = { path = "../volatile" }

[features]
std = []
